import os
from selenium import webdriver
driver = webdriver.Chrome("C:\\Users\\mInE\\Downloads\\Compressed\\chromedriver.exe")
driver.get('http://facebook.com')
driver.maximize_window()
#driver.get_screenshot_as_file("ss2.png")
driver.find_element_by_id("u_0_j").send_keys("Aman Kumar")
driver.find_element_by_id("u_0_l").send_keys("Shrivastava")
driver.find_element_by_id("u_0_o").send_keys("Shrivastavaaman446@gmail.com")
driver.find_element_by_id("u_0_r").send_keys("Shrivastavaaman446@gmail.com")
driver.find_element_by_id("u_0_v").send_keys("password123")
driver.find_element_by_id("day").send_keys("19")
driver.find_element_by_id("month").send_keys("Aug")
driver.find_element_by_id("year").send_keys("1992")
driver.find_element_by_id("u_0_a").click()
driver.find_element_by_id("u_0_a").click()
driver.find_element_by_id("u_0_11").click()
#driver.find_element_by_class("placeholder-t9h8").send_keys("Hi this is an automated message")
#driver.get_screenshot_as_file("ss3.png")
